In [1]:
import pandas as pd

In [2]:
from sklearn.ensemble import RandomForestClassifier

In [7]:
data = pd.read_excel("iris-train.xlsx")

In [9]:
data.head()

   slength  sepalwidth  petallength  petlawidth          flower
0      7.9         3.8          6.4         2.0  Iris-virginica
1      7.7         3.8          6.7         2.2  Iris-virginica
2      7.7         3.0          6.1         2.3  Iris-virginica
3      7.7         2.8          6.7         2.0  Iris-virginica
4      7.7         2.6          6.9         2.3  Iris-virginica

In [10]:
x = data.iloc[:, :-1]

In [11]:
x

     slength  sepalwidth  petallength  petlawidth
0        7.9         3.8          6.4         2.0
1        7.7         3.8          6.7         2.2
2        7.7         3.0          6.1         2.3
3        7.7         2.8          6.7         2.0
4        7.7         2.6          6.9         2.3
..       ...         ...          ...         ...
111      4.5         2.3          1.3         0.3
112      4.4         3.2          1.3         0.2
113      4.4         3.0          1.3         0.2
114      4.4         2.9          1.4         0.2
115      4.3         3.0          1.1         0.1

[116 rows x 4 columns]

In [12]:
y = data.iloc[:, -1]

In [13]:
y

0      Iris-virginica
1      Iris-virginica
2      Iris-virginica
3      Iris-virginica
4      Iris-virginica
            ...
111       Iris-setosa
112       Iris-setosa
113       Iris-setosa
114       Iris-setosa
115       Iris-setosa
Name: flower, Length: 116, dtype: object

In [14]:
model = RandomForestClassifier()

In [15]:
model.fit(x, y)

RandomForestClassifier()

In [19]:
model.predict([[5.4, 3, 4.5, 1.5]])

C:\Users\akash\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Iris-versicolor'], dtype=object)

In [20]:
datatest = pd.read_excel("iris-test.xlsx")

In [22]:
x_test = datatest.iloc[:, :-1]

In [23]:
model.predict(x_test.values)

C:\Users\akash\anaconda3\Lib\site-packages\sklearn\utils\validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

array(['Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa', 'Iris-setosa', 'Iris-versicolor', 'Iris-versicolor',
       'Iris-setosa', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa',
       'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa', 'Iris-setosa',
       'Iris-setosa'], dtype=object)